graph TD;
    d31((d3)) -- 1 --> d21((d2));
    d31 --> actElse>roll-roll-roll];
    d21 -- 2 --> d11((d1));
    d11 -- 4 --> act421>keep-kep-kep];
    d11 --> actx21>roll-keep-keep];
    d21 --> d22((d2));
    d22 -- 1--> act111>keep-keep-keep];
    d22 --> actx11>roll-keep-keep];
